using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Dolphin.Freight.Migrations
{
    public partial class Insert_Records_AppSysCodes_AmsNoId_EManifestId : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'ATH', 'ATH')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BAL', 'BAL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BBL', 'BBL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BDG', 'BDG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BDL', 'BDL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BEM', 'BEM')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BIC', 'BIC')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BIN', 'BIN')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BKG', 'BKG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BLK', 'BLK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BLT', 'BLT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BOB', 'BOB')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BOT', 'BOT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BOX', 'BOX')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BRC', 'BRC')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BRG', 'BRG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BSK', 'BSK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BXI', 'BXI')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'BXT', 'BXT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CAG', 'CAG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CAN', 'CAN')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CAR', 'CAR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CAS', 'CAS')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CBC', 'CBC')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CBY', 'CBY')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CC5', 'CC5')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CHE', 'CHE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CHS', 'CHS')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CLD', 'CLD')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CNA', 'CNA')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CNB', 'CNB')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CNC', 'CNC')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CND', 'CND')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CNE', 'CNE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CNF', 'CNF')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CNT', 'CNT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CNX', 'CNX')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'COL', 'COL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CON', 'CON')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'COR', 'COR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CRD', 'CRD')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CRF', 'CRF')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CRT', 'CRT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CSK', 'CSK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CTN', 'CTN')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CUB', 'CUB')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'CYL', 'CYL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'DBK', 'DBK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'DRK', 'DRK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'DRM', 'DRM')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'DSK', 'DSK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'DTB', 'DTB')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'DUF', 'DUF')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'EGG', 'EGG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'ENV', 'ENV')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'EPR', 'EPR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'FIR', 'FIR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'FLO', 'FLO')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'FLX', 'FLX')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'FRM', 'FRM')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'FSK', 'FSK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'FWR', 'FWR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'GOH', 'GOH')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'HED', 'HED')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'HGH', 'HGH')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'HPR', 'HPR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'HPT', 'HPT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'HRB', 'HRB')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'HRK', 'HRK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'HTB', 'HTB')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'JAR', 'JAR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'JUG', 'JUG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'KEG', 'KEG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'KIT', 'KIT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'KRK', 'KRK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'KTB', 'KTB')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'LBK', 'LBK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'LID', 'LID')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'LIF', 'LIF')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'LNR', 'LNR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'LOG', 'LOG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'LSE', 'LSE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'LUG', 'LUG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'LVN', 'LVN')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'MIX', 'MIX')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'MLV', 'MLV')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'MRP', 'MRP')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'MSV', 'MSV')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'MXD', 'MXD')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'NOL', 'NOL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'OVW', 'OVW')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PAF', 'PAF')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PAL', 'PAL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PAT', 'PAT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PCE', 'PCE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PCK', 'PCK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PCS', 'PCS')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PIR', 'PIR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PKG', 'PKG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PLC', 'PLC')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PLF', 'PLF')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PLL', 'PLL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PLN', 'PLN')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PLT', 'PLT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'POV', 'POV')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PRK', 'PRK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'PRT', 'PRT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'QTR', 'QTR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'RAL', 'RAL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'RCK', 'RCK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'REL', 'REL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'RFT', 'RFT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'ROL', 'ROL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'RVR', 'RVR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SAK', 'SAK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SBC', 'SBC')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SCS', 'SCS')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SHK', 'SHK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SHT', 'SHT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SHW', 'SHW')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SID', 'SID')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SKD', 'SKD')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SKE', 'SKE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SLP', 'SLP')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SLV', 'SLV')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SPI', 'SPI')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SPL', 'SPL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SPR', 'SPR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'SVN', 'SVN')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TBE', 'TBE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TBN', 'TBN')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TKR', 'TKR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TKT', 'TKT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TLD', 'TLD')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TNK', 'TNK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TRC', 'TRC')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TRI', 'TRI')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TRK', 'TRK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TRU', 'TRU')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TRY', 'TRY')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TSS', 'TSS')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TTC', 'TTC')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'TUB', 'TUB')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'UNP', 'UNP')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'UNT', 'UNT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'VEH', 'VEH')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'VPK', 'VPK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'WHE', 'WHE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'WLC', 'WLC')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'EManifestId', GETDATE(), 'WRP', 'WRP')");

            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Barrel', 'Barrel')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bundle', 'Bundle')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Beam', 'Beam')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bing Chest', 'Bing Chest')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bin', 'Bin')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bulk Bag', 'Bulk Bag')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bucket', 'Bucket')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bale', 'Bale')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bulk', 'Bulk')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bobbin', 'Bobbin')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bottle', 'Bottle')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Box', 'Box')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Barge', 'Barge')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Basket', 'Basket')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Box with inner container', 'Box with inner container')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Bucket', 'Bucket')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Cabinet', 'Cabinet')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Cage', 'Cage')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Carcass', 'Carcass')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Case', 'Case')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Container Bulk Cargo', 'Container Bulk Cargo')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Carboy', 'Carboy')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Can Case', 'Can Case')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Cheeses', 'Cheeses')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Chest', 'Chest')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Car Load, Rail', 'Car Load, Rail')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Container MAC-ISO, Light weight 8x8x20 foot air', 'Container MAC-ISO, Light weight 8x8x20 foot air')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Container, Navy Cargo Transporter', 'Container, Navy Cargo Transporter')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Container, Commercial Highway lift', 'Container, Commercial Highway lift')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Engine Container', 'Engine Container')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Multiwall Container Secured to Warehouse Pallet', 'Multiwall Container Secured to Warehouse Pallet')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Container (Not used in Sea AMS)', 'Container (Not used in Sea AMS)')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'CONEX Container, express', 'CONEX Container, express')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Coil', 'Coil')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Cones', 'Cones')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Cord', 'Cord')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Cradle', 'Cradle')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Crate', 'Crate')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Cask', 'Cask')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Carton', 'Carton')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Cube', 'Cube')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Cylinder', 'Cylinder')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Dry Bulk', 'Dry Bulk')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Double Leneth Rack', 'Double Leneth Rack')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Drum', 'Drum')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Double Length Skid', 'Double Length Skid')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Double Leneth Toe Bin', 'Double Leneth Toe Bin')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Duffel Bag', 'Duffel Bag')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Envelope', 'Envelope')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Firkin', 'Firkin')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Flo-Bin', 'Flo-Bin')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Liner Bag Liquid', 'Liner Bag Liquid')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Frame', 'Frame')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Flask', 'Flask')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Forward', 'Forward')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Gallon', 'Gallon')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Garments on Hangers', 'Garments on Hangers')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Heads of Beef', 'Heads of Beef')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Hogshead', 'Hogshead')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Hamper', 'Hamper')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Hopper Truck', 'Hopper Truck')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'On Hanger or Rack in Boxes', 'On Hanger or Rack in Boxes')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Half Standard Rack', 'Half Standard Rack')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Half Standard Tote Bin', 'Half Standard Tote Bin')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Jar', 'Jar')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Jug', 'Jug')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Keg', 'Keg')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Kit', 'Kit')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Knockdown Rack', 'Knockdown Rack')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Knockdown Tote Bin', 'Knockdown Tote Bin')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Liquid Bulk', 'Liquid Bulk')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Lifts', 'Lifts')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Logs', 'Logs')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Loose', 'Loose')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Lugs', 'Lugs')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Lift Van', 'Lift Van')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'MILVAN Military Van', 'MILVAN Military Van')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Multi Roll Pack', 'Multi Roll Pack')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'MSCVAN Military Sealift Command Van', 'MSCVAN Military Sealift Command Van')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Mixed Type Pack', 'Mixed Type Pack')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Noil', 'Noil')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Overwrap', 'Overwrap')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Pail', 'Pail')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Packed not otherwise specified', 'Packed not otherwise specified')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Parcel', 'Parcel')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Pims', 'Pims')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Package', 'Package')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Pieces', 'Pieces')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Platform', 'Platform')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Pipeline', 'Pipeline')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Pallet (Not used in Sea AMS)', 'Pallet (Not used in Sea AMS)')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Private Vehicle', 'Private Vehicle')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Pipe Rack', 'Pipe Rack')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Quarters of Beef', 'Quarters of Beef')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Rail (Semiconductor)', 'Rail (Semiconductor)')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Rack', 'Rack')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Reel', 'Reel')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Roll', 'Roll')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Reverse Reel', 'Reverse Reel')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Sack', 'Sack')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Liner Bag Dry', 'Liner Bag Dry')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Suitcase', 'Suitcase')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Shook', 'Shook')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Sheet', 'Sheet')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Sides of Beef', 'Sides of Beef')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Skid', 'Skid')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Skid elevating or lift truck', 'Skid elevating or lift truck')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Slip Sheet', 'Slip Sheet')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Sleeve', 'Sleeve')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Sin Cylinders', 'Sin Cylinders')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Spool', 'Spool')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'SEAVAN Sea Van', 'SEAVAN Sea Van')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tube', 'Tube')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tote Bin', 'Tote Bin')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tin', 'Tin')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tank Car', 'Tank Car')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tank Truck', 'Tank Truck')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Intermodal Trailer/Container Load (Rail)', 'Intermodal Trailer/Container Load (Rail)')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tank', 'Tank')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tierce', 'Tierce')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tri-Wall Box', 'Tri-Wall Box')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Trunk or Chest', 'Trunk or Chest')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tray', 'Tray')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Trunk, Salesmen Sample', 'Trunk, Salesmen Sample')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tote Can', 'Tote Can')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Tub', 'Tub')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Unpacked', 'Unpacked')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Unit', 'Unit')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Vehicles', 'Vehicles')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Van Pack', 'Van Pack')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Wooden Case', 'Wooden Case')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'On Own Wheels', 'On Own Wheels')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Wheeled Carrier', 'Wheeled Carrier')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'Wrapped', 'Wrapped')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'ACRE', 'ACRE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'BAR', 'BAR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'BARREL', 'BARREL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'BUN', 'BUN')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'CUBIC-MTR', 'CUBIC-MTR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'HUNDRED', 'HUNDRED')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'CUP', 'CUP')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'DECALITRE', 'DECALITRE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'DECANTER', 'DECANTER')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'DECALITRE', 'DECALITRE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'GRAM', 'GRAM')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'GIGA-WATHR', 'GIGA-WATHR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'KILOGRAM', 'KILOGRAM')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'LOT', 'LOT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'LITRE OF ALCOHOL', 'LITRE OF ALCOHOL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'LITRE', 'LITRE')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'THOUSAND', 'THOUSAND')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'SQUARE-MTR', 'SQUARE-MTR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'CUBIC-MTR', 'CUBIC-MTR')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'METER', 'METER')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'MUG', 'MUG')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'NUMBER', 'NUMBER')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'PARCEL', 'PARCEL')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'POUCH', 'POUCH')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'SKID', 'SKID')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'SLOT', 'SLOT')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'STICK', 'STICK')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'TEN', 'TEN')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'TONNES', 'TONNES')");
            migrationBuilder.Sql("INSERT INTO AppSysCodes(Id, CodeType, CreationTime, CodeValue, ShowName) VALUES (NEWID(), 'AmsNoId', GETDATE(), 'TEN PAIRS', 'TEN PAIRS')");
        } 

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            
        }
    }
}
